src/components/SplashScreen.vue, src/main.js, src/store.js
* When you go to to the Fire map, you should see the same blocking "Loading data please wait..." until the underlying data has been loaded.
* pending HTTP request state is saved in the store.
=> manage pending http request count in store

.gitignore, package-lock.json
Reverts ua-snap/mapvue#8
Hey, I'm sorry to be late looking at this -- I'd started to but got distracted -- I think we may have gone the wrong direction on this.  While some specific projects/repos have specific reasons to not use the lock file, I think it's actually the right case for us because:
* The [documentation](https://docs.npmjs.com/files/package-lock.json) suggests doing it, and
* It solves the problem we've had in the past with version drift.
* Even locking down dependencies in our `package.json` isn't as good as the `package-lock` because the `package-lock` is recursive.
I think the pain point we experienced here -- lots of noisy shifts in the package.json -- is down to two reasons:
1. New project = lots of new/shifting dependencies while lots of new things are brought into the …
=> Revert "Adds package-lock.json to .gitignore as it is auto-generated."

src/components/Maps/AK_Fires_Graph.vue
Previously, when you had navigated to the Fire map then gone to another map, the `window.resize` event wasn't cleared so there was a JS console error because the Plotly element wasn't present on the new map.  This fixes that error.  To test, go to the Fire map, look at the graph, then go back to the main screen, then go to the IAM map.  There should be no JS error.
There still may be some jank with the graph resizing properly (see #14).
=> destroy Fire plotly object & release window resize event

src/components/Map.vue, src/store.js
Previous behavior was that switching between maps (open a map, then click "About this site & other maps", then clicking another map) failed to show the Splash screen.  Added a cleanup hook to the `Map` component and the store.
=> ensure splash screen is displayed when switching maps

src/components/LayerMenu.vue, src/components/LayerMenuButtonItem.vue, src/components/Maps/AK_Fires.vue, src/components/Maps/IAM.vue
Previously, the "Show Fire Graph" button was put in the `LayerMenu` component, so it rendered on every map.  That's not right!
This PR fixes this by:
* Create a new component, `LayerMenuButtonItem` (name ok?) to implement the buttons
* Accept a new prop, `buttons`, from the parent component (which is one of the maps, like `AK_Fires.vue`) which is an array of button definitions.  If present, these are rendered.
* Move custom button definition/code into the map that needs it, out of `LayerMenu`.  Both the Fire and IAM map have custom buttons.
* Replace existing buttons to use new `LayerMenuButtonItem` components.
Caveats/notes:
* This code no longer switches to show dual icons when Dual Maps is disabled vs. one icon when enabled.  I chose to do this because it simplifies the code (all …
=> Implement better way to handle custom map buttons in LayerMenu

src/components/Maps/AK_Fires.vue, src/components/Maps/AK_Fires_Graph.vue, src/store.js
This pull request refactors the state used by the Fire map out of the global store and into a dynamic module which is registered in the store.  There are no user-facing changes to behavior.
There will likely be a merge conflict or something needing resolution with pull request #21, because the code responsible for showing/hiding the fire chart is being moved around there.  Depending on the order these get merged, the correct code will need to be put into place to test this.
=> refactor fire map state out of global store object

src/components/Maps/AK_Fires.vue
Minor performance boost here (thought it would be more noticeable).  Was attempting to reduce the lag between activating/showing the Fire Layer and when it appears (less than a second but still laggy).  The only further performance improvement for the future I can think of would be to render and then adjust transparency/visibility instead of adding/removing the layer from the map, and that'd be a much different rewrite.
=> remove fire icon from scope of Vue component

src/components/Maps/IAM.vue
This commit implements/changes:
* Basic tour functionality now in place
* I did not implement some of the fancy zoom-to-view stuff (possible, but it seemed superfluous)
* Removed the query to GeoServer for the perimeter of the IAM study area, it's already present on the map the whole time.
Some things to consider before merging:
* Is it OK that the first popup box covers the main area of the screen?  It's possible (though it wasn't obvious) how to get more control over the positioning of that box, but I didn't think the juice was worth the squeeze initially here.
* Is it OK to lose some of the panning/zooming?
Bugs/non-features:
* The overall state of the map could use more cleanup/setup when initiating the tour
* No back button by default in Shepherd 😶 ...can add but it makes more …
=> adds IAM tour

src/components/Maps/AK_Fires.vue, src/components/Maps/AK_Fires_Graph.vue
1. Timeout was too short by default for `axios`, which left the app in a broken state (not fully handled here).  Set to 2 minutes.  This is because it can take quite a while for the upstream API to refresh and regenerate.
2. Missing fire data yielded an error on the JS console for the AK_Fires_Graph component, fixed with a guard clause.
How to test:
* Open new terminal session, then `nc -l 2389` (Assumes `netcat` is installed)
* Edit `config/prod.env.js` and set `FIRE_FEATURES_URL: '"http://localhost:2389"'`
* Restart dev server (needed because the env variables changed here are only updated upon server restart)
* Go to fire map and enjoy 2 minutes of restful peace as no data is loaded.  (You can see the request piped to the screen via `nc` though).
Then you'll be able to get the expected …
=> Catch and handle two cases which caused errors

src/components/MapInstanceWrapper.vue, src/styles.scss
Keep map-specific styles out of `styles.scss` unless we really have to.  Test: the map title should appear in the normal place (upper-left), nothing else broken.
=> move common map styles to MapInstanceWrapper

src/components/Map.vue
I'm not certain why this was removed (perhaps a goof commit) but it's probably wired up better this way anyhow.  Things to check:
* Is the zoom control present & functional?
* what about with split maps?
=> Fixes #33, restore zoom control

src/components/LayerList.vue
Restores ability to drag and drop.
The problem was a weird one: the vue `draggable` requires that the immediate child be a container for the draggable elements -- but we'd put in a placeholder for the tours as the immediate child, so that broke the draggable.  Kind of subtle.
Things to check here:
* Does the drag and drop for sort order work?
* Do any tours that rely on those steps still run properly?
=> Fixes #36, repair drag and drop layer order

src/components/Maps/AK_Fires_Graph.vue
I just changed the text to make it more clear that this graphy only applies May 1 - Sept 30.  The data feed supplying this will start presenting 2018 data on May 1.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/67)
=> Ref #54, update fire graph

layer_configurations/big_fire_years.sld, src/components/Map.vue, src/components/Maps/AK_Fires.vue, src/components/Maps/AK_Fires_Graph.vue
This is done by applying a different style to the same shapefile used for historical data, so there are some changes to pass that WMS request (styles) across.  Also, since 'name' was used as a unique key field in a few places, the code now checks (and uses) "layerName" for the name of the layer, which need not be unique.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/86)
=> Closes #61, adds "recent high fire season" layer.

src/components/MapList.vue
To test -- look at the `src/maps.js` and note which have `draft: true`.  These maps shouldn't be listed on the home page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/96)
=> hide draft maps

package-lock.json, package.json, src/components/Maps/AK_Fires.vue, src/main.js
To test:
- Ensure that the Fire map loads normally in any browser other than IE11
- Then, log into an IE11/Win7 machine and see how it works!  Previously, only a single fire would be shown when you clicked "Show Map."  You should now see all the fires that are present.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/106)
=> Implements workaround so fire layer loads normally in IE11/Win7

config/prod.env.js, src/components/LayerMenu.vue, src/components/MapLayer.vue, src/components/Maps/AK_Fires.vue, src/components/Maps/AK_Fires_Graph.vue, src/components/Maps/IAM.vue, src/main.js
This PR resolves #108 and #117 along with adding additional custom Google Analytics tags for events such as toggling map layer, click dataset information, and toggling the dual maps / sync maps functionality.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/118)
=> Tour analytics

layer_configurations/historical-fire-perimeters.css, src/components/Maps/AK_Fires.vue
Updates the name, legend, and style reference for the fire history layer.
New SLD to be used in GeoServer is added in the `layer_configurations` directory.  This is already present / configured on the production server, but to test this, you need to point your dev instance at the production instance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/163)
=> Rename fire history layer, update styles for layer

src/components/Maps/AK_Fires.vue, src/router/index.js
This bypasses the splash screen, too.
URL to test should be: http://localhost:8080/#/map/fires/graph
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/169)
=> Adds a way to go directly to the fire graph.

src/components/MapLayer.vue, src/store.js
Local layers (GeoJSON, markers, polygons) don't do the left/right split map thing.  So, don't show left/right controls for that layer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/170)
=> Hide left/right controls when a layer is local

config/prod.env.js, src/components/Maps/AK_Fires.vue
See issues #155, #154.
App now processes data from remote geojson/json files instead of hitting an endpoint.  For this branch to work, you must be testing against an updated version of the mv-aicc-shim (check with me if unclear where/what that is).
VIIRS data now renders as simple GeoJSON layer, no CSS animations.  Performance is improved.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/171)
=> Fetch fire data statically & reformat VIIRS to not use animation

src/store.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/175)
=> Fixes #149, don't reorder layers based on activating that layer

src/components/Maps/AK_Fires.vue
Test this by ensuring that the text is complete, and that 2019 fires show up in both the big fire year and historical perimeter layers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/202)
=> Fixes #199, updates text for 2019 

src/components/Map.vue, src/components/MapLayer.vue
First test is to verify that cache hits are happening.
1. Go to the Fire map
2. Activate dev console, go to Network tab, and clear it out so there's nothing showing there.
3. Toggle the Land Cover layer on.
4. Examine the network request for one of the WMS requests (lots fire off at the same time, there should be a bunch).  Find the response headers.
Expected: response header `geowebcache-cache-result: HIT`
Second test is to confirm that layers with configurable properties (date, scenario, etc) show the right thing when the layer is toggled on/off.
1. Go to the Fire Map, click Show Map.
2. Activate the "Historical lightning strikes" layer, which defaults to May.
3. Change the month to July.
4. Toggle the layer off, then back on again.
Expected: the drop-down control shows July, not May. …
=> Fix layer refresh & cache issues
