ua-snap/mapvue

index.html
package-lock.json
package.json
src/components/LayerMenu.vue
src/components/Maps/AK_Fires.vue
src/components/Maps/AK_Fires_Graph.vue
src/components/SplashScreen.vue
src/main.js
src/store.js

What's working:
- Graph now fetches and displays data
- There's a button to toggle graph visibility added to the layer sidebar
What's not working (yet):
- Some CSS is still wrong
- ~~Need to see if the resizing works properly~~ Horizontal resize works, I just can't really test or work on vertical resize unless I do crazy things to my monitor 😄 
- The button to toggle graph visibility is present for all maps!  Should fix in future refactoring, not in this branch

Makes the fire graph work

---

README.md
package-lock.json
package.json
src/components/LayerMenu.vue
src/components/Map.vue
src/components/MapLayer.vue
src/components/Maps/AK_Fires.vue
src/components/Maps/SNAP_RCP6.vue
src/main.js
src/store.js

Things in this PR to check:
Some things that aren't working here:
- Fire map's layer of fire data isn't displaying
- Generally we don't have the "special map layers" hooked into this yet (special meaning layers that are coded instead of being just fetched from GeoServer).

Working split maps

---

src/App.vue
src/components/LayerMenuButtonItem.vue
src/components/Loading.vue
src/components/MapInstance.vue
src/components/MapInstanceWrapper.vue
src/global.scss
src/main.js

Tracked in issue #30 .
* fix include order of bootstrap & our style files
* include map component code via lazy load
* fix some typos in <style> component declarations
Testing:
* Start by generating the production bundle and running it locally: `npm run build && cd dist && python -m SimpleHTTPServer` and open `http://localhost:8000`.  At the same time, in another terminal window run the normal `npm run dev` and open that on `http://localhost:8080` for comparison.
* Do styles look correct / the same between the two versions on the home screen?
* Navigate to the Fire map.  Do you see a "Hang on, getting ready..." message?  *I think this one may not be working properly yet, try it on the dev instance vs. the generated bundle, what's up?  Chat with BC about this when you do it please*

Fix issues needed before doing production deploy

---

layer_configurations/README.md
layer_configurations/aaokh_ice_extent.sld

This is mainly a placeholder folder where we can put SLDs and other specific layer configurations which will normally live inside GeoServer.  Sometimes the SLD docs are a bit complicated, so I wanted to have them in version control.

adds layer configs folder to track SLDs

---

.babelrc
build/webpack.base.conf.js
config/index.js
package-lock.json
package.json

update to support IE11 and compress files

---

package-lock.json
src/components/Maps/AAOKH.vue
src/components/Maps/AK_Fires.vue

Also removes some code duplication from AAOKH styles, and adds HTML legends for Fire map.
Check that dates are right everywhere for this layer, I may have missed one.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/65)

Fixes #53, updates historical layer

---

src/components/Maps/AK_Fires.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/64)

Fix #55, update text of fire splash screen

---

src/components/Maps/AAOKH.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/66)

Clean up incorrect HTML & styling for AAOKH sidebar legend

---

config/dev.env.js
config/prod.env.js
src/components/Maps/AK_Fires.vue

Things to check here:
* Performance!  The glowing animation (CSS3 transition) may be too processor-heavy to actually use.  It does make my laptop sing a little bit.  Could also use an animated GIF or something.  Thoughts?
* Need real sidebar stuff
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/68)

Closes #59, adds VIIRS hotspot data layer

---

src/components/LayerMenu.vue
src/components/LayerMenuButtonItem.vue
src/components/MapLayer.vue
src/store.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/70)

Closes #69, visually quiet layer menu

---

src/components/Tour.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/82)

Closes #80, close Tour when changing screens

---

package-lock.json
package.json
src/components/LayerList.vue
src/components/MapLayer.vue
src/components/Maps/AK_Fires.vue
src/global.scss

When the feature count is zero for lightning or VIIRS, the layer is greyed out, title strikethrough, unclickable and a hover message shows a descriptive message.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/84)

Fixes #79, tell user if no data present for a layer.

---

src/components/Hello.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/91)

make copyright date dynamic

---

package-lock.json
package.json
src/components/Maps/AK_Fires.vue
src/main.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/92)

remove localstorage from fire map

---

config/dev.env.js
src/components/LayerMenu.vue
src/components/Maps/AK_Fires.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/95)

unbreak the fire tour

---

src/components/Maps/AK_Fires.vue
src/components/Maps/IAM.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/107)

add workspace prefix to enable cache

---

src/components/Maps/AK_Fires.vue

* No more Lightning popup
* No more opacity based on time
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/113)

Fixes #109, reduce amount of lightning shown on map

---

config/dev.env.js
src/components/Maps/AK_Fires.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/120)

Add relative flammability

---

src/components/Maps/AK_Fires.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/124)

Fire halo markers

---

.gitignore
habitat/README.md
habitat/default.toml
habitat/hooks/run
habitat/plan.sh
package-lock.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/129)

Habitat integration for MapVue.

---

.gitignore
config/dev.env.js
package-lock.json
package.json
src/components/DateScenarioSelector.vue
src/components/LayerList.vue
src/components/LayerMenu.vue
src/components/Map.vue
src/components/MapInstance.vue
src/components/MapInstanceWrapper.vue
src/components/MapLayer.vue
src/components/Maps/AAOKH.vue
src/components/Maps/AK_Fires.vue
src/components/Maps/IAM.vue
src/components/Maps/SNAP_RCP6.vue
src/store.js

Implements split map swiper and dynamic decade/scenario selectors.  (I should have split these out, sorry!).
There's a bit more work to do (see review comments).
This branch needs to be tested with all existing tours + maps to ensure that there's no breakage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/132)

Split map swiper

---

src/components/Maps/SNAP_RCP6.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/140)

Fixes #137, #138, Update links to Community Charts

---

src/components/Map.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/142)

Fixes #135, refresh layers after opening split map

---

src/components/Maps/AK_Fires.vue
src/components/Maps/AK_Fires_Graph.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/143)

Fire map fixup

---

src/components/Maps/AK_Fires.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/168)

Fix #164, add link to air quality information

---

package-lock.json
package.json
src/components/MapInstanceWrapper.vue
src/components/Maps/AK_Fires.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/177)

Switch VIIRS layer to heatmap

---

src/components/Footer.vue
src/components/Hello.vue
src/components/Maps/AaokhSplashScreen.vue
src/components/SplashScreen.vue

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/186)

Fix broken links

---

.eslintrc.js
config/dev.env.js
config/prod.env.js
package-lock.json
package.json
src/App.vue
src/components/Footer.vue
src/components/Map.vue
src/components/MapInstanceWrapper.vue
src/components/MapLayer.vue
src/components/MapList.vue
src/components/Maps/AAOKH.vue
src/components/Maps/AK_Fires.vue
src/components/Maps/IAM.vue
src/components/Maps/SNAP_RCP6.vue
src/components/Sidebar.vue
src/components/Tour.vue
src/main.js
src/maps.js
src/store.js

Makes a few final adjustments needed to get the launch stable & on known backend APIs.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ua-snap/mapvue/201)

Merge V2.2.1
